name: kat
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter 

  cupertino_icons: ^1.0.2

  firebase_core: ^2.4.1
  cloud_firestore: ^4.3.1
  firebase_storage: ^11.0.10
  firebase_auth: ^4.2.4
  google_sign_in: ^5.4.2

  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^2.1.1
  
  logger: ^1.1.0

  equatable: ^2.0.5
  go_router: ^5.2.0
  easy_localization: ^3.0.1
  elegant_notification: ^1.6.4
  uuid: ^3.0.7
  google_fonts: ^3.0.1
  get_storage: ^2.0.3
  image_picker: ^0.8.6
  font_awesome_flutter: ^10.3.0
  lottie: ^2.1.0
  validators: ^3.0.0
  url_strategy: ^0.2.0
  page_transition: ^2.0.9
  responsive_framework: ^0.2.0
  flutter_bounceable: ^1.1.0
  cached_network_image: ^3.2.3
  flutter_staggered_grid_view: ^0.6.2
  pie_menu: ^1.2.6
  http: ^0.13.5
  image_network: ^2.5.1
  search_choices: ^2.2.1
  retry: ^3.1.0
  http_status_code: ^0.0.2
  bordered_text: ^2.0.0
  screenshot: ^1.3.0
  image_gallery_saver: ^1.7.1
  flutter_cache_manager: ^3.3.0 
  full_screen_image_null_safe: ^2.0.0
  riverpod_annotation: ^1.1.1
  animated_text_kit: ^4.2.2
  molten_navigationbar_flutter: ^1.0.1
  flutter_native_timezone: ^2.0.0
  timezone: ^0.9.1
  flutter_local_notifications: ^13.0.0
  shimmer: ^2.0.0
  awesome_bottom_bar: ^1.2.2
  firebase_messaging: ^14.2.1
  persistent_bottom_nav_bar_v2: ^4.2.6
  share_plus: ^6.3.0
  path_provider: ^2.0.12
  flag: ^6.0.0
  dash_flags: ^0.0.3
  flutter_advanced_switch: ^3.0.1
  webview_flutter: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

  riverpod_generator: ^1.0.6
  build_runner: ^2.3.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/anims/
    - assets/fonts/
    - assets/translations/

  fonts:
    - family: Ukrainian Princess Shadow
      fonts:
        - asset: assets/fonts/UkrainianPrincessShadow.ttf

    - family: Ukrainian Princess
      fonts:
        - asset: assets/fonts/UkrainianPrincess.ttf
       