name: kat
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter 

  cupertino_icons: ^1.0.2

  firebase_core: ^2.4.1
  cloud_firestore: ^4.3.1
  firebase_storage: ^11.0.10
  firebase_auth: ^4.2.4
  google_sign_in: ^5.4.2

  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^2.1.1
  
  logger: ^1.1.0

  equatable: ^2.0.5
  go_router: ^5.2.0
  easy_localization: ^3.0.1
  elegant_notification: ^1.6.4
  uuid: ^3.0.7
  google_fonts: ^3.0.1
  get_storage: ^2.0.3
  image_picker: ^0.8.6
  font_awesome_flutter: ^10.3.0
  lottie: ^2.1.0
  validators: ^3.0.0
  url_strategy: ^0.2.0
  page_transition: ^2.0.9
  responsive_framework: ^0.2.0
  flutter_bounceable: ^1.1.0
  cached_network_image: ^3.2.3
  flutter_staggered_grid_view: ^0.6.2
  pie_menu: ^1.2.6
  http: ^0.13.5
  image_network: ^2.5.1
  search_choices: ^2.2.1
  retry: ^3.1.0
  http_status_code: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

  riverpod_generator: ^1.0.6
  build_runner: ^2.3.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/anims/
    - assets/fonts/
    - assets/translations/

  fonts:
    - family: Ukrainian Princess Shadow
      fonts:
        - asset: assets/fonts/UkrainianPrincessShadow.ttf

    - family: Ukrainian Princess
      fonts:
        - asset: assets/fonts/UkrainianPrincess.ttf
       